version: 2.1

orbs:
  go: circleci/go@3.0.3
  aws-ecr: circleci/aws-ecr@9.7.0
  aws-cli: circleci/aws-cli@5.4.1

jobs:
  verification:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - go/load-mod-cache
      - go/mod-download
      - go/save-mod-cache
      - run:
          name: Install golangci-lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.5.0
      - run:
          name: Run linter
          command: golangci-lint run

  build-amd64:
    docker:
      - image: cimg/base:current
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          role_arn: ${DEV_AWS_ROLE_ARN}
          region: us-east-1
      - aws-ecr/build_image:
          account_id: ${DEV_AWS_ACCOUNT_ID}
          platform: linux/amd64
          no_output_timeout: 30m
          public_registry: true
          public_registry_alias: aikido-security-staging
          push_image: true
          repo: kubernetes-sbom-collector
          tag: ${CIRCLE_SHA1}-amd64
          region: us-east-1

  build-arm64:
    docker:
      - image: cimg/base:current
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          role_arn: ${DEV_AWS_ROLE_ARN}
          region: us-east-1
      - aws-ecr/build_image:
          account_id: ${DEV_AWS_ACCOUNT_ID}
          platform: linux/arm64
          no_output_timeout: 30m
          public_registry: true
          public_registry_alias: aikido-security-staging
          push_image: true
          repo: kubernetes-sbom-collector
          tag: ${CIRCLE_SHA1}-arm64
          region: us-east-1

  create-manifest:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - go/install
      - run:
          name: Install crane
          command: go install github.com/google/go-containerregistry/cmd/crane@v0.20.6
      - aws-cli/setup:
          role_arn: ${DEV_AWS_ROLE_ARN}
          region: us-east-1
      - run:
          name: Create multi-arch manifest
          command: |
            aws ecr-public get-login-password --region us-east-1 | crane auth login --username AWS --password-stdin public.ecr.aws

            crane index append \
              -m public.ecr.aws/aikido-security-staging/kubernetes-sbom-collector:${CIRCLE_SHA1} \
              public.ecr.aws/aikido-security-staging/kubernetes-sbom-collector:${CIRCLE_SHA1}-amd64 \
              public.ecr.aws/aikido-security-staging/kubernetes-sbom-collector:${CIRCLE_SHA1}-arm64

            crane tag public.ecr.aws/aikido-security-staging/kubernetes-sbom-collector:${CIRCLE_SHA1} latest

  release:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - run:
          name: Run go-semantic-release
          command: |
            curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release
            chmod +x ./semantic-release
            ./semantic-release
            if [ -f .version ]; then
              echo "export VERSION=$(cat .version)" >> $BASH_ENV
              echo "Version detected: $(cat .version)"
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .version

  promote-to-production:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - attach_workspace:
          at: .
      - go/load-mod-cache
      - go/mod-download
      - go/save-mod-cache
      - go/install
      - run:
          name: Install crane
          command: go install github.com/google/go-containerregistry/cmd/crane@v0.20.6
      # Assume PROD role and log into production ECR Public
      - aws-cli/setup:
          role_arn: ${PROD_AWS_ROLE_ARN}
          region: us-east-1
      - run:
          name: Login to PROD ECR Public and promote image
          command: |
            aws ecr-public get-login-password --region us-east-1 | crane auth login --username AWS --password-stdin public.ecr.aws

            if [ -f .version ]; then
              VERSION=$(cat .version)
            else
              echo "Missing .version file" && exit 1
            fi
            echo "Promoting version v$VERSION to production..."
            crane copy \
              public.ecr.aws/aikido-security-staging/kubernetes-sbom-collector:${CIRCLE_SHA1} \
              ${PROD_ECR_REPO}:v${VERSION}

workflows:
  pull-request:
    jobs:
      - verification:
          filters:
            branches:
              ignore: main

  main-deploy:
    jobs:
      - build-amd64:
          filters:
            branches:
              only: main
          context: staging
      - build-arm64:
          filters:
            branches:
              only: main
          context: staging
      - create-manifest:
          requires:
            - build-amd64
            - build-arm64
          filters:
            branches:
              only: main
          context: staging

  production-release:
    when:
      condition: false
    jobs:
      - release:
          type: approval
          context: production
      - promote-to-production:
          requires:
            - release
          context: production
