name: '[Production] Release and push image'

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: standard-runner-no-rights-public-ip
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    outputs:
      version: ${{ steps.version-set.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run go-semantic-release
        id: semantic
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Version Output
        id: version-set
        if: steps.semantic.outputs.version != ''
        run: echo "version=${{ steps.semantic.outputs.version }}" >> "$GITHUB_OUTPUT"

  docker:
    runs-on: standard-runner-no-rights-public-ip
    permissions:
      id-token: write
      contents: read
    needs: release
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      DEV_AWS_ROLE_ARN: ${{ vars.DEV_AWS_ROLE_ARN }}
      PROD_AWS_ROLE_ARN: ${{ vars.PROD_AWS_ROLE_ARN }}
      DEV_ECR_REPO: ${{ vars.DEV_ECR_REPO }}
      PROD_ECR_REPO: ${{ vars.PROD_ECR_REPO }}
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS credentials (Staging)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'us-east-1'
          role-to-assume: ${{ env.DEV_AWS_ROLE_ARN }}

      - name: Login to Staging ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Configure AWS credentials (Production)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'us-east-1'
          role-to-assume: ${{ env.PROD_AWS_ROLE_ARN }}

      - name: Login to Production ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install crane
        run: |
          go install github.com/google/go-containerregistry/cmd/crane@v0.21.4
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Promote image to production
        run: |
          crane copy \
            ${{ env.DEV_ECR_REPO }}:${{ github.sha }} \
            ${{ env.PROD_ECR_REPO }}:v${{ needs.release.outputs.version }}
